"""
Build a single-file submission for IMC Prosperity 4.

Takes trained policy weights (.npz) and assembles them with the feature
computation and numpy inference code into one standalone .py file.

Usage:
    python -m RLM.shared.build_submission \
        --weights RLM/double_dqn/policy_weights/best_model.npz \
        --model-type mlp \
        --output submissions/RL_SUBMISSION.py
"""

import argparse
import numpy as np
import os
import sys
import textwrap


def weights_to_python_source(npz_path):
    """Convert .npz weight file to Python source code with numpy arrays."""
    data = np.load(npz_path)
    lines = []
    lines.append("# === Policy Weights (auto-generated) ===")
    lines.append("import numpy as np")
    lines.append("")

    for key in sorted(data.files):
        arr = data[key]
        arr_repr = repr(arr.tolist())
        lines.append(f"WEIGHTS_{key.upper()} = np.array({arr_repr}, dtype=np.float32)")

    lines.append("")
    lines.append("POLICY_WEIGHTS = {")
    for key in sorted(data.files):
        lines.append(f'    "{key}": WEIGHTS_{key.upper()},')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def build_submission(weights_path, model_type="mlp", output_path=None):
    """Assemble a complete submission file.

    Args:
        weights_path: Path to .npz weight file.
        model_type: "mlp", "dueling", "ensemble", or "lstm".
        output_path: Output .py file path.
    """
    weights_source = weights_to_python_source(weights_path)

    # The submission template includes everything needed inline
    template = textwrap.dedent('''
    """
    RL Trading Agent - IMC Prosperity 4
    Generated by RLM build_submission.py
    Model type: {model_type}
    """

    from datamodel import Listing, Observation, Order, OrderDepth, ProsperityEncoder, Symbol, Trade, TradingState
    from typing import Dict, List
    import json
    import numpy as np
    from collections import deque

    # =============================================================================
    # Configuration
    # =============================================================================
    PRODUCTS = {products}
    POSITION_LIMITS = {position_limits}
    NUM_ACTIONS = {num_actions}
    HISTORY_LENGTH = {history_length}
    CLIP_FEATURES = {clip_features}

    ACTION_PARAMS = {action_params}

    {weights_source}

    # =============================================================================
    # Feature computation (inline from shared/features.py)
    # =============================================================================
    def compute_features(bid_prices, bid_volumes, ask_prices, ask_volumes,
                         position, position_limit, mid_prices_history,
                         returns_history, trades=None, entry_value=0.0,
                         trade_buy_vols=None, trade_sell_vols=None, trade_counts=None):
        """Compute 19 trading features from current market state."""
        bid_p = [p for p in bid_prices if p is not None and p == p]
        bid_v = [v for v, p in zip(bid_volumes, bid_prices) if p is not None and p == p]
        ask_p = [p for p in ask_prices if p is not None and p == p]
        ask_v = [v for v, p in zip(ask_volumes, ask_prices) if p is not None and p == p]

        best_bid = bid_p[0] if bid_p else 0
        best_ask = ask_p[0] if ask_p else 0
        best_bid_vol = bid_v[0] if bid_v else 1
        best_ask_vol = ask_v[0] if ask_v else 1
        total_bid_vol = sum(bid_v) if bid_v else 1
        total_ask_vol = sum(ask_v) if ask_v else 1

        mid_price = (best_bid + best_ask) / 2.0 if (best_bid and best_ask) else 0
        if best_bid and best_ask:
            micro_price = (best_bid * best_ask_vol + best_ask * best_bid_vol) / (best_bid_vol + best_ask_vol)
        else:
            micro_price = mid_price

        spread = best_ask - best_bid if (best_bid and best_ask) else 0
        spread_bps = (spread / mid_price * 10000) if mid_price > 0 else 0

        mid_prices_history.append(mid_price)
        if len(mid_prices_history) >= 2:
            ret = (mid_prices_history[-1] - mid_prices_history[-2]) / mid_prices_history[-2] if mid_prices_history[-2] != 0 else 0
            returns_history.append(ret)

        if len(mid_prices_history) >= 20:
            rolling_mean = np.mean(list(mid_prices_history)[-20:])
            mid_price_norm = (mid_price - rolling_mean) / rolling_mean if rolling_mean != 0 else 0
        else:
            mid_price_norm = 0.0

        micro_price_norm = (micro_price - mid_price) / spread if spread > 0 else 0.0

        imbalance_l1 = best_bid_vol / (best_bid_vol + best_ask_vol)
        imbalance_total = total_bid_vol / (total_bid_vol + total_ask_vol)
        depth_ratio = np.clip(total_bid_vol / total_ask_vol, 0.1, 10.0)
        book_pressure = (best_bid_vol - best_ask_vol) / (best_bid_vol + best_ask_vol)
        depth_concentration = bid_v[0] / total_bid_vol if (bid_v and total_bid_vol > 0) else 0.5

        returns_list = list(returns_history)
        return_5 = sum(returns_list[-5:]) if len(returns_list) >= 5 else 0.0
        return_20 = sum(returns_list[-20:]) if len(returns_list) >= 20 else 0.0
        return_100 = sum(returns_list[-100:]) if len(returns_list) >= 100 else 0.0

        if len(returns_list) >= 10:
            price_acceleration = sum(returns_list[-5:]) - sum(returns_list[-10:-5])
        else:
            price_acceleration = 0.0

        rolling_vol_50 = float(np.std(returns_list[-50:])) if len(returns_list) >= 50 else 0.0
        rolling_vol_200 = float(np.std(returns_list[-200:])) if len(returns_list) >= 200 else rolling_vol_50

        if trades:
            buy_vol, sell_vol = 0, 0
            for tp, tq in trades:
                if tp > mid_price:
                    buy_vol += abs(tq)
                elif tp < mid_price:
                    sell_vol += abs(tq)
                else:
                    buy_vol += abs(tq) / 2
                    sell_vol += abs(tq) / 2
            trade_buy_vols.append(buy_vol)
            trade_sell_vols.append(sell_vol)
            trade_counts.append(len(trades))
        else:
            trade_buy_vols.append(0)
            trade_sell_vols.append(0)
            trade_counts.append(0)

        total_buy = sum(trade_buy_vols)
        total_sell = sum(trade_sell_vols)
        total_flow = total_buy + total_sell
        trade_flow_imbalance = (total_buy - total_sell) / total_flow if total_flow > 0 else 0.0
        trade_intensity = np.mean(list(trade_counts)) / 5.0 if trade_counts else 0

        position_normalized = position / position_limit if position_limit > 0 else 0
        if mid_price > 0 and position != 0:
            position_pnl = (position * mid_price - entry_value) / (mid_price * position_limit)
        else:
            position_pnl = 0.0

        return np.array([
            mid_price_norm, micro_price_norm, spread, spread_bps,
            imbalance_l1, imbalance_total, depth_ratio, book_pressure, depth_concentration,
            return_5, return_20, return_100, price_acceleration,
            rolling_vol_50, rolling_vol_200,
            trade_flow_imbalance, trade_intensity,
            position_normalized, position_pnl,
        ], dtype=np.float32)


    # =============================================================================
    # Numpy inference
    # =============================================================================
    {inference_code}


    # =============================================================================
    # Trader class
    # =============================================================================
    class Trader:
        def __init__(self):
            self.policy = {policy_init}
            self.history = {{}}
            self.entry_values = {{}}

        def run(self, state: TradingState) -> tuple[dict[str, list[Order]], int, str]:
            result: Dict[str, List[Order]] = {{}}

            # Restore history from traderData
            if state.traderData:
                try:
                    saved = json.loads(state.traderData)
                    self.history = {{}}
                    for product, h in saved.get("history", {{}}).items():
                        self.history[product] = {{
                            "mid_prices": deque(h.get("mid_prices", []), maxlen=HISTORY_LENGTH),
                            "returns": deque(h.get("returns", []), maxlen=HISTORY_LENGTH),
                            "trade_buy_vols": deque(h.get("trade_buy_vols", []), maxlen=50),
                            "trade_sell_vols": deque(h.get("trade_sell_vols", []), maxlen=50),
                            "trade_counts": deque(h.get("trade_counts", []), maxlen=50),
                        }}
                    self.entry_values = saved.get("entry_values", {{}})
                except (json.JSONDecodeError, KeyError):
                    pass

            all_features = []
            products_to_trade = []

            for product in PRODUCTS:
                if product not in state.order_depths:
                    continue

                products_to_trade.append(product)
                order_depth = state.order_depths[product]

                # Initialize history if needed
                if product not in self.history:
                    self.history[product] = {{
                        "mid_prices": deque(maxlen=HISTORY_LENGTH),
                        "returns": deque(maxlen=HISTORY_LENGTH),
                        "trade_buy_vols": deque(maxlen=50),
                        "trade_sell_vols": deque(maxlen=50),
                        "trade_counts": deque(maxlen=50),
                    }}
                if product not in self.entry_values:
                    self.entry_values[product] = 0.0

                # Extract order book
                bids = sorted(order_depth.buy_orders.keys(), reverse=True)
                asks = sorted(order_depth.sell_orders.keys())

                bid_prices = [bids[i] if i < len(bids) else None for i in range(3)]
                bid_volumes = [order_depth.buy_orders.get(bid_prices[i], 0) if bid_prices[i] else 0 for i in range(3)]
                ask_prices = [asks[i] if i < len(asks) else None for i in range(3)]
                ask_volumes = [abs(order_depth.sell_orders.get(ask_prices[i], 0)) if ask_prices[i] else 0 for i in range(3)]

                # Get trades
                trades = None
                if product in state.market_trades:
                    trades = [(t.price, t.quantity) for t in state.market_trades[product]]

                position = state.position.get(product, 0)
                h = self.history[product]

                features = compute_features(
                    bid_prices, bid_volumes, ask_prices, ask_volumes,
                    position, POSITION_LIMITS.get(product, 50),
                    h["mid_prices"], h["returns"],
                    trades, self.entry_values[product],
                    h["trade_buy_vols"], h["trade_sell_vols"], h["trade_counts"],
                )

                # Normalize
                feat_means = POLICY_WEIGHTS.get("feature_means", np.zeros(19))
                feat_stds = POLICY_WEIGHTS.get("feature_stds", np.ones(19))
                features = np.clip((features - feat_means) / (feat_stds + 1e-8), -CLIP_FEATURES, CLIP_FEATURES)

                all_features.append(features)

            if not all_features:
                return result, 0, state.traderData or ""

            obs = np.concatenate(all_features)
            action, _ = self.policy.predict(obs, normalize=False)

            # Decode action into per-product actions
            product_actions = []
            remaining = action
            for _ in range(len(products_to_trade)):
                product_actions.append(remaining % NUM_ACTIONS)
                remaining //= NUM_ACTIONS

            # Convert actions to orders
            for product, act_id in zip(products_to_trade, product_actions):
                orders = self._action_to_orders(product, act_id, state)
                if orders:
                    result[product] = orders

            # Save history
            save_data = {{
                "history": {{p: {{k: list(v) for k, v in h.items()}} for p, h in self.history.items()}},
                "entry_values": self.entry_values,
            }}
            traderData = json.dumps(save_data)

            return result, 0, traderData

        def _action_to_orders(self, product, action_id, state):
            """Convert action ID to Order objects."""
            params = ACTION_PARAMS[action_id]
            if params["type"] == "hold":
                return []

            order_depth = state.order_depths[product]
            bids = sorted(order_depth.buy_orders.keys(), reverse=True)
            asks = sorted(order_depth.sell_orders.keys())

            if not bids or not asks:
                return []

            best_bid = bids[0]
            best_ask = asks[0]
            pos = state.position.get(product, 0)
            pos_limit = POSITION_LIMITS.get(product, 50)

            side = params["side"]
            qty = params["qty"]

            if params["type"] == "cross":
                if side == "buy":
                    qty = min(qty, pos_limit - pos)
                    if qty <= 0:
                        return []
                    return [Order(product, best_ask, qty)]
                else:
                    qty = min(qty, pos_limit + pos)
                    if qty <= 0:
                        return []
                    return [Order(product, best_bid, -qty)]

            elif params["type"] == "passive":
                offset = params.get("offset", 0)
                if side == "buy":
                    price = best_bid - offset
                    qty = min(qty, pos_limit - pos)
                    if qty <= 0:
                        return []
                    return [Order(product, price, qty)]
                else:
                    price = best_ask + offset
                    qty = min(qty, pos_limit + pos)
                    if qty <= 0:
                        return []
                    return [Order(product, price, -qty)]

            return []
    ''').strip()

    # Model-specific inference code
    if model_type == "mlp":
        inference_code = textwrap.dedent('''
    def numpy_relu(x):
        return np.maximum(0, x)

    class PolicyNet:
        def __init__(self, weights):
            self.weights = weights

        def predict(self, features, normalize=False):
            x = features.astype(np.float32)
            layer_idx = 0
            while f"W{layer_idx}" in self.weights:
                W = self.weights[f"W{layer_idx}"]
                B = self.weights[f"B{layer_idx}"]
                x = x @ W.T + B
                if f"W{layer_idx + 1}" in self.weights:
                    x = numpy_relu(x)
                layer_idx += 1
            return int(np.argmax(x)), x
        ''').strip()
        policy_init = "PolicyNet(POLICY_WEIGHTS)"

    elif model_type == "dueling":
        inference_code = textwrap.dedent('''
    def numpy_relu(x):
        return np.maximum(0, x)

    class PolicyNet:
        def __init__(self, weights):
            self.weights = weights

        def predict(self, features, normalize=False):
            x = features.astype(np.float32)
            idx = 0
            while f"shared_W{idx}" in self.weights:
                x = numpy_relu(x @ self.weights[f"shared_W{idx}"].T + self.weights[f"shared_B{idx}"])
                idx += 1
            v, a = x.copy(), x.copy()
            vi = 0
            while f"value_W{vi}" in self.weights:
                v = v @ self.weights[f"value_W{vi}"].T + self.weights[f"value_B{vi}"]
                if f"value_W{vi+1}" in self.weights: v = numpy_relu(v)
                vi += 1
            ai = 0
            while f"advantage_W{ai}" in self.weights:
                a = a @ self.weights[f"advantage_W{ai}"].T + self.weights[f"advantage_B{ai}"]
                if f"advantage_W{ai+1}" in self.weights: a = numpy_relu(a)
                ai += 1
            q = v + a - np.mean(a)
            return int(np.argmax(q)), q
        ''').strip()
        policy_init = "PolicyNet(POLICY_WEIGHTS)"

    elif model_type == "ensemble":
        inference_code = textwrap.dedent('''
    def numpy_relu(x):
        return np.maximum(0, x)

    class SingleNet:
        def __init__(self, weights, prefix=""):
            self.weights = weights
            self.prefix = prefix

        def forward(self, x):
            layer_idx = 0
            while f"{self.prefix}W{layer_idx}" in self.weights:
                W = self.weights[f"{self.prefix}W{layer_idx}"]
                B = self.weights[f"{self.prefix}B{layer_idx}"]
                x = x @ W.T + B
                if f"{self.prefix}W{layer_idx + 1}" in self.weights:
                    x = numpy_relu(x)
                layer_idx += 1
            return x

    class PolicyNet:
        def __init__(self, weights):
            self.weights = weights
            self.nets = []
            i = 0
            while f"m{i}_W0" in weights:
                self.nets.append(SingleNet(weights, prefix=f"m{i}_"))
                i += 1
            if not self.nets:
                self.nets.append(SingleNet(weights, prefix=""))

        def predict(self, features, normalize=False):
            x = features.astype(np.float32)
            all_q = [net.forward(x) for net in self.nets]
            avg_q = np.mean(all_q, axis=0)
            return int(np.argmax(avg_q)), avg_q
        ''').strip()
        policy_init = "PolicyNet(POLICY_WEIGHTS)"

    elif model_type == "lstm":
        inference_code = textwrap.dedent('''
    def numpy_relu(x):
        return np.maximum(0, x)

    class PolicyNet:
        def __init__(self, weights):
            self.weights = weights
            hs = int(weights.get("lstm_hidden_size", np.array(64)).item())
            self.h = np.zeros(hs, dtype=np.float32)
            self.c = np.zeros(hs, dtype=np.float32)

        def _sigmoid(self, x):
            return 1.0 / (1.0 + np.exp(-np.clip(x, -15, 15)))

        def predict(self, features, normalize=False):
            x = features.astype(np.float32)
            w = self.weights
            i = self._sigmoid(x @ w["lstm_W_ii"].T + self.h @ w["lstm_W_hi"].T + w["lstm_b_i"])
            f = self._sigmoid(x @ w["lstm_W_if"].T + self.h @ w["lstm_W_hf"].T + w["lstm_b_f"])
            g = np.tanh(x @ w["lstm_W_ig"].T + self.h @ w["lstm_W_hg"].T + w["lstm_b_g"])
            o = self._sigmoid(x @ w["lstm_W_io"].T + self.h @ w["lstm_W_ho"].T + w["lstm_b_o"])
            self.c = f * self.c + i * g
            self.h = o * np.tanh(self.c)
            h = self.h
            idx = 0
            while f"head_W{idx}" in w:
                h = h @ w[f"head_W{idx}"].T + w[f"head_B{idx}"]
                if f"head_W{idx+1}" in w: h = numpy_relu(h)
                idx += 1
            return int(np.argmax(h)), h
        ''').strip()
        policy_init = "PolicyNet(POLICY_WEIGHTS)"
    else:
        raise ValueError(f"Unknown model type: {model_type}")

    # Import config values
    from .config import PRODUCTS, POSITION_LIMITS, NUM_ACTIONS, ACTION_PARAMS, ENV_CONFIG

    submission = template.format(
        model_type=model_type,
        products=repr(PRODUCTS),
        position_limits=repr(POSITION_LIMITS),
        num_actions=NUM_ACTIONS,
        history_length=ENV_CONFIG["history_length"],
        clip_features=ENV_CONFIG["clip_features"],
        action_params=repr(ACTION_PARAMS),
        weights_source=weights_source,
        inference_code=inference_code,
        policy_init=policy_init,
    )

    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w") as f:
            f.write(submission)
        print(f"Submission written to: {output_path}")
        print(f"Model type: {model_type}")
        print(f"File size: {os.path.getsize(output_path) / 1024:.1f} KB")
    else:
        print(submission)

    return submission


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build Prosperity 4 submission")
    parser.add_argument("--weights", required=True, help="Path to .npz weight file")
    parser.add_argument("--model-type", default="mlp", choices=["mlp", "dueling", "ensemble", "lstm"])
    parser.add_argument("--output", default=None, help="Output .py file path")
    args = parser.parse_args()

    build_submission(args.weights, args.model_type, args.output)
